title: HHEU Unconference
email: hello@hackathonhackers.eu
author: HHEU
description: Unconference for UK and EU hackathon organisers & Hackcon Digital watch party
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hackathonhackers.eu" # the base hostname & protocol for your site, e.g. http://example.com

# Custom options
# ticket_link: https://tickets.hackathonhackers.eu
schedule_link: //schedule

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
